apiVersion: aiven.nais.io/v1
kind: AivenApplication
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  kafka:
    pool: nav-infrastructure
  secretName: aiven-{{ .Release.Name }}