apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
rules:
  - apiGroups:
      - '*'
    resources:
      - 'applications'
      - 'aivenapplications'
      - 'azureadapplications'
      - 'cronjobs'
      - 'deployments'
      - 'endpoints'
      - 'events'
      - 'horizontalpodautoscalers'
      - 'iampolicies'
      - 'iampolicymembers'
      - 'iamserviceaccounts'
      - 'idportenclients'
      - 'ingresses'
      - 'jwkers'
      - 'jobs'
      - 'leases'
      - 'maskinportenclients'
      - 'naisjobs'
      - 'namespaces'
      - 'networkpolicies'
      - 'rolebindings'
      - 'roles'
      - 'secrets'
      - 'serviceaccounts'
      - 'services'
      - 'sqldatabases'
      - 'sqlinstances'
      - 'sqlusers'
      - 'storagebucketaccesscontrols'
      - 'storagebuckets'
      - 'poddisruptionbudgets'
      - 'bigquerydatasets'
      - 'streams'
      - 'podmonitors'
    verbs:
      - 'get'
      - 'create'
      - 'update'
      - 'delete'
      - 'patch'
      - 'list'
      - 'watch'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
