apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ .Release.Name }}
    {{- toYaml .Values.labels | nindent 4 }}
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Release.Name }}
        {{- toYaml .Values.labels | nindent 8 }}
    spec:
      containers:
      - env:
        - name: STAKATER_NAISERATOR_SECRET
          value: {{ .Values.stakaterSecret }}
        image: ghcr.io/nais/naiserator/naiserator:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: naiserator
        volumeMounts:
        - mountPath: /etc/naiserator.yaml
          name: naiserator
          subPath: naiserator.yaml
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-cert
          readOnly: true
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      serviceAccount: {{ .Release.Name }}
      serviceAccountName: {{ .Release.Name }}
      volumes:
      - name: naiserator
        secret:
          defaultMode: 420
          secretName: {{ .Release.Name }}
      - name: webhook-cert
        secret:
          defaultMode: 420
          secretName: {{ .Release.Name }}-webhook
