apiVersion: v1
kind: Secret
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ .Release.Name }}-webhook
  name: naiserator-webhook-certificates
type: kubernetes.io/Opaque
data:
  tls.crt: 
  tls.key: 
