apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: testapp
  namespace: default
  labels:
    team: aura
spec:
  image: jhrv/testapp:latest
  port: 8080 
  ingresses: 
    - "https://testapp.nais.preprod.local"
