---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: naiserator
  name: naiserator
rules:
  - apiGroups:
      - '*'
    resources:
      - 'applications'
      - 'deployments'
      - 'endpoints'
      - 'events'
      - 'horizontalpodautoscalers'
      - 'iampolicies'
      - 'iampolicymembers'
      - 'iamserviceaccounts'
      - 'ingresses'
      - 'namespaces'
      - 'networkpolicies'
      - 'rolebindings'
      - 'roles'
      - 'secrets'
      - 'serviceaccounts'
      - 'serviceentries'
      - 'servicerolebindings'
      - 'serviceroles'
      - 'services'
      - 'sqldatabases'
      - 'sqlinstances'
      - 'sqlusers'
      - 'storagebucketaccesscontrols'
      - 'storagebuckets'
      - 'virtualservices'
    verbs:
      - 'get'
      - 'create'
      - 'update'
      - 'delete'
      - 'patch'
      - 'list'
      - 'watch'
