---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: naiserator
  namespace: nais
  labels:
    app: naiserator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: naiserator
  template:
    metadata:
      labels:
        app: naiserator
    spec:
      serviceAccountName: naiserator
      containers:
      - name: naiserator
        image: navikt/naiserator:latest
