name: Have you remembered to run code generation

on: push

env:
  REPO_URL: https://api.github.com/repos/nais/naiserator/dispatches

jobs:
  make-crd:
    name: Checking for missing code generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Go get controller-gen
        run: |
          export GO111MODULE=off
          dest=$(mktemp -d)
          git clone -b v0.2.5 https://github.com/kubernetes-sigs/controller-tools ${dest}
          cd ${dest}/cmd/controller-gen
          go get -v
          go install .
      - name: Go get goimports
        run: GO111MODULE=off go get golang.org/x/tools/cmd/goimports
      - name: Run code generation
        run: make crd codegen-crd codegen-updater
      - name: Check if no diff
        run: |
          test -z "$(git ls-files --exclude-standard --others)"
      - name: Code generation has been forgotten
        if: ${{ failure() }}
        run: |
          echo "Looks like you forgot to run code generation"
          git status
          git --no-pager diff
      - name: Trigger build and deploy workflow
        if: github.ref == 'refs/heads/master'
        run: |
          curl -X POST "${REPO_URL}" \
          -H 'Accept: application/vnd.github.v3+json' \
          -u ${{ secrets.NAIS_YAML_TOKEN }} \
          --data '{"event_type": "build-and-deploy"}'
