name: Validate code gen

on: push
jobs:
  make-crd:
    name: Have you rememberd to run code gen?
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Go get controller-gen
        run: go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.5
      - name: Run make crd
        run: make crd
      - name: Check if no diff
        run: git status --porcelain=v1 2>/dev/null && "git is clean"
      - name: Was there a diff?
        if: ${{ failure() }}
        run: |
          echo "Looks like you forgot to run 'make crd'"
          git status
