name: Build and deploy
on: 
  push:
    paths-ignore: 
      - charts

env:
  image: ghcr.io/${{ github.repository }}/naiserator

jobs:
  build-push:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout naiserator
        uses: actions/checkout@v2
      - name: Generate image environment variable
        run: |
          version=$(./version.sh)
          echo "IMAGE=${image}:${version}" >> $GITHUB_ENV
      - name: Build docker image
        run: docker build . --tag $IMAGE
      - name: Login to Github package registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_REPOSITORY" --password-stdin
      - name: Push docker image
        run: docker push $IMAGE

  nais-yaml:
    name: Release to nais-yaml
    runs-on: ubuntu-latest
    needs: build-push
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout naiserator
        uses: actions/checkout@v2
        with:
          path: naiserator
      - uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.NAIS_APP_PRIVATE_KEY }}
          app-id: ${{ secrets.NAIS_APP_ID }}
          repo: navikt/nais-yaml
      - name: Checkout nais-yaml
        uses: actions/checkout@v2
        with:
          repository: navikt/nais-yaml
          token: ${{ steps.get-token.outputs.token }}
          path: nais-yaml
      - name: Generate image environment variable
        run: |
          cd naiserator
          version=$(./version.sh)
          echo "version=${version}" >> $GITHUB_ENV
          echo "IMAGE=${image}:${version}" >> $GITHUB_ENV
          cd ..
      - name: Generate nais-yaml files
        run: |
          cd naiserator
          res="hack/resources"
          static_file="../nais-yaml/templates/zz-generated-naiserator.yaml"
          cat $res/00-namespace.yaml $res/01-serviceaccount.yaml $res/02-clusterrole.yaml $res/03-clusterrolebinding.yaml > $static_file
          cd ..
      - name: Update nais-yaml
        run: |
          cd nais-yaml
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          sed -E -i "s#image: ghcr.io/nais/naiserator/naiserator:.+#image: ${IMAGE}#" vars/global.yaml
          git add .
          git --no-pager diff --cached
          git status
          git commit -a -m "Bump Naiserator to version ${version}"
          git push
