name: Build and deploy
on: push

env:
  image: docker.pkg.github.com/${{ github.repository }}/naiserator

jobs:
  make-crd:
    name: Checking for missing code generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Go get controller-gen
        run: |
          dest=$(mktemp -d)
          git clone -b v0.2.5 https://github.com/kubernetes-sigs/controller-tools ${dest}
          cd ${dest}/cmd/controller-gen
          go get
          go install .
      - name: Go get goimports
        run: GO111MODULE=off go get golang.org/x/tools/cmd/goimports
      - name: Run code generation
        run: make crd codegen-crd codegen-updater
      - name: Check if no diff
        run: |
          test -z "$(git ls-files --exclude-standard --others)"
      - name: Code generation has been forgotten
        if: ${{ failure() }}
        run: |
          echo "Looks like you forgot to run code generation"
          git status
          git --no-pager diff

  build-push:
    name: Build and push image
    needs: make-crd
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout naiserator
        uses: actions/checkout@v2
      - name: Generate image environment variable
        run: |
          version=$(./version.sh)
          echo "IMAGE=${image}:${version}" >> $GITHUB_ENV
      - name: Build docker image
        run: docker build . --tag $IMAGE
      - name: Login to Github package registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com -u "$GITHUB_REPOSITORY" --password-stdin
      - name: Push docker image
        run: docker push $IMAGE

  nais-yaml:
    name: Release to nais-yaml
    runs-on: ubuntu-latest
    needs: build-push
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout naiserator
        uses: actions/checkout@v2
        with:
          path: naiserator
      - name: Checkout nais-yaml
        uses: actions/checkout@v2
        with:
          repository: navikt/nais-yaml
          token: ${{ secrets.NAIS_YAML_TOKEN }}
          path: nais-yaml
      - name: Generate image environment variable
        run: |
          cd naiserator
          version=$(./version.sh)
          echo "version=${version}" >> $GITHUB_ENV
          echo "IMAGE=${image}:${version}" >> $GITHUB_ENV
          cd ..
      - name: Generate nais-yaml files
        run: |
          cd naiserator
          res="hack/resources"
          static_file="../nais-yaml/templates/zz-generated-naiserator.yaml"
          cat $res/00-namespace.yaml $res/01-serviceaccount.yaml $res/02-clusterrole.yaml $res/03-clusterrolebinding.yaml > $static_file
          cd ..
      - name: Update nais-yaml
        run: |
          cd nais-yaml
          git config user.name "NAIS deploy pipeline"
          git config user.email "aura@nav.no"
          sed -E -i "s#image: docker.pkg.github.com/nais/naiserator/naiserator:.+#image: ${IMAGE}#" vars/naiserator.yaml
          git add .
          git --no-pager diff --cached
          git status
          git commit -a -m "Bump Naiserator to version ${version}"
          git push
