name: Build and deploy
on:
    push:
        paths-ignore:
            - "charts/**"
            - ".github/workflows/chart.yaml"

env:
    image: ghcr.io/${{ github.repository }}/naiserator

jobs:
    build-push:
        name: Build and push image
        runs-on: ubuntu-latest
        outputs:
          tag: ${{ steps.version.tag }}
        steps:
            - name: Checkout naiserator
              uses: actions/checkout@v3
            - name: Generate image environment variable
              id: version
              run: |
                  version=$(./version.sh)
                  echo "IMAGE=${image}:${version}" >> $GITHUB_ENV
                  echo "tag=${version}" >> $GITHUB_OUTPUT
            - name: Build docker image
              run: docker build . --tag $IMAGE
            - name: Login to Github package registry
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_REPOSITORY" --password-stdin
            - name: Push docker image
              if: github.ref == 'refs/heads/master'
              run: docker push $IMAGE

    rollout:
        permissions:
            id-token: write
        needs: 
            - build-push
        runs-on: fasit-deploy
        if: github.ref == 'refs/heads/master'
        steps:
            - name: debug
              run: |
                 echo '{"imageTag": "${{ needs.build-push.outputs.tag }}"}'
            - uses: nais/fasit-deploy@main
              with:
                  json: '{"imageTag": "${{ needs.build-push.outputs.tag }}"}'
                  feature_name: naiserator
