name: Build and deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths-ignore:
      - "charts/**"
      - ".github/workflows/chart.yaml"
      - "*.md"

jobs:
  build_push_sign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # ratchet:actions/checkout@v3
      - uses: nais/build-push-sign@main
        with:
          name: naiserator
          dockerfile: Dockerfile
          service_account: gh-naiserator
          push: ${{ github.actor != 'dependabot[bot]' }}
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}

  rollout:
    permissions:
      id-token: write
    needs:
      - build-push-sign
    runs-on: fasit-deploy
    if: github.ref == 'refs/heads/master'
    steps:
      - name: info
        run: |
          echo 'Rolling out: {"imageTag": "${{ needs.build-push-sign.outputs.version }}"}'
      - uses: nais/fasit-deploy@main
        with:
          json: '{"imageTag": "${{ needs.build-push-sign.outputs.version }}"}'
          feature_name: naiserator