name: Build and deploy
on: 
  repository_dispatch:
    types:
      - build-and-deploy

env:
  image: docker.pkg.github.com/${{ github.repository }}/naiserator

jobs:
  build-push:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: jitterbit/await-check-suites@v1
        with:
          onlyFirstCheckSuite: true
      - name: Checkout naiserator
        uses: actions/checkout@v2
      - name: Generate image environment variable
        run: |
          version=$(./version.sh)
          echo ::set-env name=version::${version}
          echo ::set-env name=IMAGE::${image}:${version}
      - name: Build docker image
        run: docker build . --tag $IMAGE
      - name: Login to Github package registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com -u "$GITHUB_REPOSITORY" --password-stdin
      - name: Push docker image
        run: docker push $IMAGE

  nais-yaml:
    name: Release to nais-yaml
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: Checkout naiserator
        uses: actions/checkout@v2
        with:
          path: naiserator
      - name: Generate image environment variable
        run: |
          cd naiserator
          pwd
          version=$(./version.sh)
          echo ::set-env name=version::${version}
          echo ::set-env name=IMAGE::${image}:${version}
          cd ..
          pwd
      - name: Checkout nais-yaml
        uses: actions/checkout@v2
        with:
          repository: navikt/nais-yaml
          token: ${{ secrets.NAIS_YAML_TOKEN }}
          path: nais-yaml
      - name: Update nais-yaml
        run: |
          pwd
          cd naiserator
          pwd
          ls -la
          version=$(./version.sh)
          res="hack/resources"
          static_file="../nais-yaml/templates/zz-generated-naiserator.yaml"
          cat $res/00-namespace.yaml $res/01-serviceaccount.yaml $res/02-clusterrole.yaml $res/03-clusterrolebinding.yaml config/crd/*.yaml > $static_file
          cd ../nais-yaml
          pwd
          ls -la
          git config user.name "NAIS deploy pipeline"
          git config user.email "aura@nav.no"
          sed -E -i "s#image: .+#image: ${IMAGE}#" vars/naiserator.yaml
          git add .
          git --no-pager diff --cached
          git status
          git commit -a -m "Bump Naiserator to version ${version}"
          git push
